<? $account = $this->auth()->getManager(); ?>

<nav class="navbar">
  <div class="container-fluid blackBackgroundColor">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="<?=$this->url('home')?>">
            <img class="img-responsive" src="../../../themes/elar/images/hrelp-logo-sm.gif"/>
       </a>
       <span class="tit"><a href="<?=$this->url('home')?>" class="tit"><span class="tit">Endangered Languages Archive at SOAS University of London</span></a>
     
     </div>

    <? if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <? if ($this->feedback()->tabEnabled()): ?>
        <li>
          <a id="feedbackLink" class="modal-link" href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope"></i> <?=$this->transEsc("Feedback")?></a>
        </li>
      <? endif; ?>
      <? $cart = $this->cart(); if ($cart->isActive()): ?>
        <li id="cartSummary">
          <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="fa fa-suitcase"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
        </li>
      <? endif; ?>
      <li class="dropdown">
        <a href="/" class="modal-link"><?=$this->transEsc("home")?></a>
      </li>
      <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
        <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
          <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>" class="modal-link" title="<?=$this->transEsc("Your Account")?>"><i class="fa fa-home"></i> <?$user = $account->isLoggedIn();?><?=$this->transEsc("Hello")?> <?=$user->cat_username?></a>
        </li>
        <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
          <a href="<?=$this->url('myresearch-logout')?>" class="modal-link" title="<?=$this->transEsc("Log Out")?>"><i class="fa fa-sign-out"></i> <?=$this->transEsc("Log Out")?></a>
        </li>
        <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
          <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
            <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Institutional Login")?></a>
          <? else: ?>
            <a href="<?=$this->url('myresearch-userlogin')?>" class="modal-link" title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a>
          <? endif; ?>
        </li>
      <? endif; ?>

      <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
        <li class="dropdown">
          <form method="post" name="themeForm" action="" id="themeForm">
            <input type="hidden" name="ui"/>
          </form>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <? foreach ($this->layout()->themeOptions as $current): ?>
              <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
            <? endforeach; ?>
          </ul>
        </li>
      <? endif; ?>
      
      <li class="dropdown">
      	<a href="https://lat1.lis.soas.ac.uk/ds/RRS_V1/RrsRegistration" class="modal-link" target="_blank"><?=$this->transEsc("new user")?></a>
      </li>
	
      <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
        <li class="dropdown">
          <form method="post" name="langForm" action="" id="langForm">
            <input type="hidden" name="mylang"/>
          </form>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
          <ul class="dropdown-menu">
          <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
            <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
          <? endforeach; ?>
          </ul>
        </li>
      <? endif; ?> 
    </ul>
  </div>
  <div id="sBox" class="well well-lg clearfix navbar-form">
  	<?=$this->render("search/searchbox.phtml")?>
  </div>
  
  
  <? endif; ?>
    
  </div>
</nav>
