#!/bin/sh
PATH=$PATH:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
export PATH
export VUFIND_HOME=/usr/local/vufind/
export VUFIND_LOCAL_DIR=/usr/local/vufind/local
find  /usr/local/vufind/local/harvest/Authors/processed/ -name '*.xml' -exec rm {} \;
find  $VUFIND_HOME/local/harvest/ELAR/processed/ -name '*.xml' | xargs cp -t $VUFIND_HOME/local/harvest/Authors/
cd /usr/local/vufind/harvest
/usr/local/vufind/harvest/batch-import-xsl-auth.sh ./Authors/ ../import/authors.properties
find  /usr/local/vufind/local/harvest/Authors/ -name '*.xml' -exec rm {} \;
