function filterELARWebTrafficUploadedfilesSortPrivate() {
    
    var dateFrom = document.getElementById('datepickerFrom');
    var dateTo = document.getElementById('datepickerTo');

    var selectedFB = new Array();
    $("input:checkbox[name=fundingbody]:checked").each(function(){
        selectedFB.push($(this).val());
    });

    var selectedCS = new Array();
    $("input:checkbox[name=current_or_superseded]:checked").each(function(){
        selectedCS.push($(this).val());
    });

    var funding_body = selectedFB;
    var current_superseded = selectedCS;
    
    //console.log(dateFrom.value);
    //console.log(dateTo.value);
    
    var dF = dateFrom.value.split("/");
    var dT = dateTo.value.split("/");
    
    var dayFrom = dF[0];
    var monthFrom = dF[1];
    var yearFrom = dF[2];
    var dayTo = dT[0];
    var monthTo = dT[1];
    var yearTo = dT[2];
    
    //console.log(dayFrom);
    //console.log(monthFrom);
    //console.log(yearFrom);
    //console.log(dayTo);
    //console.log(monthTo);
    //console.log(yearTo);
    
    var monthNames = ["","January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
    ];
    
    //var y = document.getElementById('years');
    //var m = document.getElementById('months');
    
    //var year = y.value;
    //var month = m.value;
    
    //console.log(year);
    //console.log(month);
    
    checkUploadedFilesSort(yearFrom, monthFrom, dayFrom, yearTo, monthTo, dayTo,0,funding_body, current_superseded,"deposit_id", "both");
 
    document.getElementById("statisticsFormUploadedFiles").action="PrivateStatsUploadedfiles?yearFrom="+yearFrom+"&monthFrom="+monthFrom+"&dayFrom="+dayFrom+"&yearTo="+yearTo+"&monthTo="+monthTo+"&dayTo="+dayTo+"&funding_body="+funding_body+"&current_superseded="+current_superseded+"&source=ajax";
    
    var contentFrom = "<i>" + yearFrom + " " + monthNames[Number(monthFrom)] + " " + dayFrom + "</i>";
    document.getElementsByClassName("labelPublicStatsResultsFrom")[0].innerHTML = contentFrom;
    var contentTo = "<i>" + yearTo + " " + monthNames[Number(monthTo)] + " " + dayTo + "</i>";
    document.getElementsByClassName("labelPublicStatsResultsTo")[0].innerHTML = contentTo;
    
}


function checkUploadedFilesSort(yearFrom, monthFrom, dayFrom, yearTo, monthTo, dayTo, page,funding_body,current_superseded, type, sort) {

  var content = '';
  var limit = '';
  header = "<thead><tr><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";

  if (type=='deposit_id'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"desc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }



  if (type=='deposit_title'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"desc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }
  if (type=='uploaded_date'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"desc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }
  if (type=='bundle_id'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"desc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }
  if (type=='file_name'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"assc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"desc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }
  if (type=='access'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"desc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }
  if (type=='size'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"desc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }
  if (type=='duration'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"desc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }
  if (type=='file_type'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"desc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }
  if (type=='funding_body'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"desc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }
  if (type=='cs'){
    if(sort=='asc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortasc'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"desc\");'>C/S</a></th></tr></thead>";
    if(sort=='desc')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortdesc'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
    if(sort=='both')   header = "<thead><tr><th class='col-sm-2 table-align thdeposit_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_id\",\"asc\");'>Deposit ID</a></th><th class='col-sm-2 table-align thdeposit_title sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"deposit_title\",\"asc\");'>Deposit Title</a></th><th class='col-sm-2 table-align thuploaded_date sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"uploaded_date\",\"asc\");'>Uploaded Date</a></th><th class='col-sm-2 table-align thbundle_id sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"bundle_id\",\"asc\");'>Bundle ID</a></th><th class='col-sm-2 table-align thfile_name sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_name\",\"asc\");'>File Name</a></th><th class='col-sm-2 table-align thaccess sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"access\",\"asc\");'>Access</a></th><th class='col-sm-2 table-align thsize sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"size\",\"asc\");'>Size (bytes)</a></th><th class='col-sm-2 table-align thduration sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"duration\",\"asc\");'>Duration (seconds)</a></th><th class='col-sm-2 table-align thfile_type sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"file_type\",\"asc\");'>File type</a></th><th class='col-sm-2 table-align thfunding_body sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"funding_body\",\"asc\");'>Funding body</a></th><th class='col-sm-2 table-align thcs sortboth'><a type='button' onclick='refreshUploadedFilesSort(0,\"cs\",\"asc\");'>C/S</a></th></tr></thead>";
  }







  $.ajax({
    dataType: 'json',
    url: path + '/AJAX/JSON?method=getUploadedFilesSort',
    data: {yearFrom:yearFrom, monthFrom:monthFrom, dayFrom:dayFrom, yearTo:yearTo, monthTo:monthTo, dayTo:dayTo, page:page, funding_body:funding_body, current_superseded:current_superseded, type:type, sort:sort},
    success: function(response) {
      content = "<table id='example33' class='table table-striped table-bordered' cellspacing='0' width='auto'>"+header+"<tbody>";
      if(response.status == 'OK' && response.data != null) {
        $.each(response.data, function(i, result) {
          //console.log(result.name);
          //console.log(result.firstname);
          //console.log(result.surname);
          //console.log(result.email);
          //console.log(result.user_id);
          
          content = content + "<tr><td role='row'>" + result.deposit_id +"</td>";
          content = content + "<td role='row'>" + result.deposit_title +"</td>";
          content = content + "<td role='row'>" + result.date +"</td>";
          //content = content + "<td role='row'>" + result.bundle_id +"</td>";
	  content = content + "<td><a href='/Record/" + result.bundle_id + "' target='_blank'>" + result.bundle_id + "</a></td>";
          //content = content + "<td role='row'>" + result.bundle_title +"</td>";
          content = content + "<td role='row'>" + result.file_name +"</td>";
          content = content + "<td role='row'>" + result.access +"</td>";
          content = content + "<td role='row'>" + result.size +"</td>";
          content = content + "<td role='row'>" + result.duration +"</td>";
          content = content + "<td role='row'>" + result.file_type +"</td>";
          content = content + "<td role='row'>" + result.funding_body +"</td>";
          content = content + "<td role='row'>" + result.current_or_superseded +"</td>";
          content = content + "</tr>";
          total = result.count;
          
	  if(i+1 == '10000')
	  {
		limit = '1';
	  }

        });
      }
      content = content + "</tbody></table>";

      document.getElementById("pageUpload").style.display = "none";
      previo = parseInt(page)-1;
      previo =  previo+"";
      siguiente = parseInt(page)+1;
      siguiente = siguiente+"";
      total = parseInt(total);
      if (previo=='-1') {
          if (total>10) {
              document.getElementById("pageUpload").style.display = "block";
              document.getElementById("pageUpload").innerHTML ="<a class='btn btn-default' type='button' onclick='refreshUploadedFilesSort("+siguiente+",\""+type+"\",\""+sort+"\");'><i class='fa fa-angle-right' aria-hidden='true'></i> Next</a>";
          }
      }
      else {
          if (siguiente > total/10 && previo!='-1') {
              document.getElementById("pageUpload").style.display = "block";
              document.getElementById("pageUpload").innerHTML ="<a class='btn btn-default' type='button' onclick='refreshUploadedFilesSort("+previo+",\""+type+"\",\""+sort+"\");'><i class='fa fa-angle-left' aria-hidden='true'></i> Prev</a>";
          }
          else {
              document.getElementById("pageUpload").style.display = "block";
              document.getElementById("pageUpload").innerHTML ="<a class='btn btn-default' type='button' onclick='refreshUploadedFilesSort("+previo+",\""+type+"\",\""+sort+"\");'><i class='fa fa-angle-left' aria-hidden='true'></i> Prev</a>"+"<a class='btn btn-default' type='button' onclick='refreshUploadedFilesSort("+siguiente+",\""+type+"\",\""+sort+"\");'><i class='fa fa-angle-right' aria-hidden='true'></i> Next</a>";
          }
      }


      document.getElementById("example3_wrapper").innerHTML = content;
     //document.getElementsByClassName("dataTables_wrapper")[2].innerHTML = content;

      document.getElementById("limit_alert").style.display = "none";
      if(limit == '1') {
      	document.getElementById("limit_alert").style.display = "block";
      }

      
      $('#example3').DataTable( {
        "lengthMenu": [[100], ["All"]]
    } );
    
    
      
    }
  });
}

function refreshUploadedFilesSort(page, type, sort) {
    var dateFrom = document.getElementById('datepickerFrom');
    var dateTo = document.getElementById('datepickerTo');

    var dF = dateFrom.value.split("/");
    var dT = dateTo.value.split("/");

    var dayFrom = dF[0];
    var monthFrom = dF[1];
    var yearFrom = dF[2];
    var dayTo = dT[0];
    var monthTo = dT[1];
    var yearTo = dT[2];

    var selectedFB = new Array();
    $("input:checkbox[name=fundingbody]:checked").each(function(){
        selectedFB.push($(this).val());
    });

    var selectedCS = new Array();
    $("input:checkbox[name=current_or_superseded]:checked").each(function(){
        selectedCS.push($(this).val());
    });

    var funding_body = selectedFB;
    var current_superseded = selectedCS;



    var monthNames = ["","January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
    ];

    checkUploadedFilesSort(yearFrom, monthFrom, dayFrom, yearTo, monthTo, dayTo, page, funding_body, current_superseded, type, sort);

    document.getElementById("statisticsFormUploadedFiles").action="PrivateStatsUploadbyfiletype?yearFrom="+yearFrom+"&monthFrom="+monthFrom+"&dayFrom="+dayFrom+"&yearTo="+yearTo+"&monthTo="+monthTo+"&dayTo="+dayTo+"&source=ajax";

    var contentFrom = "<i>" + yearFrom + " " + monthNames[Number(monthFrom)] + " " + dayFrom + "</i>";
    document.getElementsByClassName("labelPublicStatsResultsFrom")[0].innerHTML = contentFrom;
    var contentTo = "<i>" + yearTo + " " + monthNames[Number(monthTo)] + " " + dayTo + "</i>";
    document.getElementsByClassName("labelPublicStatsResultsTo")[0].innerHTML = contentTo;

}

