<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  //$this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Back to the result list'), '</li> ') .

    $this->layout()->breadcrumbs ='<li class="active"><a href=javascript:history.back(); >Back to the result list</a></li> ';
    //<a href=javascript:history.back()>Back to the result list</a>
  $this->layout()->title = $this->driver->getShortTitle();
?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    #<?=$this->localizedNumber($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . $this->localizedNumber($this->scrollData['resultTotal']) . ' ' . $this->transEsc('results') ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

</br>

<div class="row">
      <? // Title - core.phtml ?>
      <?=$this->flashmessages()?>
      <?=$this->record($this->driver)->getCoreMetadata()?>
    </div>

    <? if (count($this->tabs) > 0): ?>
        <? foreach ($this->tabs as $tab => $obj): ?>
        <? // add current tab to breadcrumbs if applicable:
          $desc = $obj->getDescription();
          $tab_classes = array();
          if (0 === strcasecmp($this->activeTab, $tab)) {
            $tab_classes[] = 'active';
            //$this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
            $activeTabObj = $obj;
          }
          if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
          if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
        ?>
        <? endforeach; ?>
    <? endif; ?>

<? if($this->driver->getDeletionMessage()!='deleted') :?>
    <div class="tab-content" id="record-tabs">
      <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
        <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
      </div>
    </div>

    <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
  </div>
<? endif; ?>

<? /*
  <div class="<?=$this->layoutClass('sidebar')?>"> */ ?>
    <? /*foreach ($this->related()->getList($this->driver) as $current): */?>
      <? /*$this->related()->render($current)*/?>
    <? /*endforeach;*/?>
  <? /* </div> */ ?>
</div>
