<?
    // Set page title.
    $this->headTitle($this->translate('VuFind Administration - Private Statistics'));
?>

<? /*SCB datepicker*/ ?>

<script src="/themes/elar/js/bootstrap-datepicker.js"></script>
<link href="/themes/elar/css/datepicker.css" rel="stylesheet">
<script src="/themes/elar/js/admin/privatestatsuserdownloads.js"></script>

<? /*SCB datepicker*/ ?>

<? /*SCB mapFocus Statistics*/ ?>


  

<? /*SCB mapFocus Statistics*/ ?>

<div class="row">
  <div class="sidebar col-sm-2">
  	<?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-10">
  <? if($this->request->get('PrivateStats')== 1){ ?>

  <div class="col-sm-5">
  <div class="border-facet">
				<? 
				//$current_year = date("Y");
				//$current_month = date('m', strtotime('-1 month'))+1;
				//$month = $_GET['month'];
                                //$year = $_GET['year'];

				//if (empty($year)) $year = $current_year;
				//if (empty($month)) $month = $current_month;
				
				$today = date('d/m/Y');
				$year = date('Y');
				$month = date('m');
				$day = date('d');
				
				?>
				<p class="menuHeader">
					<?=$this->transEsc('Private Statistics')?>
				</p>
				
				<div class="contentMenu">                
					<div class="post-content-right">
					
					<div class="form-group" align="center">
						<label class="control-label" for="email_message"><?=$this->transEsc('From')?>:</label>
						  <div>
						    <input type="text" value="<?=$today;?>" data-date-format="dd/mm/yyyy" id="datepickerFrom" name="datefrom" style="text-align: center;">
						  </div>
						  <label class=" control-label" for="email_message"><?=$this->transEsc('To')?>:</label>
						  <div>
						    <input type="text" value="<?=$today;?>" data-date-format="dd/mm/yyyy" id="datepickerTo" name="dateto" style="text-align: center;">
						  </div>
					</div>
					
					<script>
						$('#datepickerFrom').datepicker({
						   weekStart: 1 // day of the week start. 0 for Sunday - 6 for Saturday
						 });
						$('#datepickerTo').datepicker({
						   weekStart: 1 // day of the week start. 0 for Sunday - 6 for Saturday
						 });
					</script>
					
					
					<style>
						.datepicker{z-index:1151 !important;}
					</style>
					
					
						<div class="form-group" align="center">
						  <? echo '<a class="btn btn-default" type="button" onclick="filterELARWebTrafficUserdownloadSortPrivate(0);"><i class="fa fa-filter" aria-hidden="true"></i> Filter</a>';?>
						</div>
						
						<div class="form-group" align="center">
						<?
						$dateObj   = DateTime::createFromFormat('!m', $month);
						$monthNameFrom = $dateObj->format('F');
						$dateObj   = DateTime::createFromFormat('!m', $month);
						$monthNameTo = $dateObj->format('F');
						?>
						<? echo '<span><i>'.$this->transEsc('Data from').' </i></span><span class="labelPublicStatsResultsFrom"><i>' . $year . ' ' . $monthNameFrom . ' ' . $day . '</i></span><i> '.$this->transEsc('to').' </i><span class="labelPublicStatsResultsTo"><i>' . $year . ' ' . $monthNameTo . ' ' . $day . '</i></span>'; ?>
						</div>
						
						<?
							$s = $this->results;
						?>
						



				   	</div>
				</div>
			</div>
		</div>
		


  <div class="col-sm-12">
  	<div class="border-facet">
				<p class="menuHeader">
					<?=$this->transEsc('User downloads')?>
				</p>
				
				
				<form id="statisticsFormUserDownload" name="statisticsFormUserDownload" action='PrivateStatsUserdownloads?yearFrom=<?=$year?>&monthFrom=<?=$month?>&dayFrom=<?=$day?>&yearTo=<?=$year?>&monthTo=<?=$month?>&dayTo=<?=$day?>' method="post">
				    <input type="hidden" name="btnExportarExcelUserDownload" value="Exportar" />
				    <p class="contentMenu">
				    <?
				    echo $this->transEsc('CSV download info');
				    ?>
				    
				    <a class="csvlink" href="#" onclick="document.getElementById('statisticsFormUserDownload').submit();" style="text-decoration: underline;">
				    <?
				    echo $this->transEsc('CSV file');
				    ?>
				    </a>
				    </p>
				</form>
				     <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">


         	<table id="example2" class="table table-striped table-bordered" cellspacing="0" width="auto">
         		<thead>
		            <tr> 
		                <th class="col-sm-2 table-align thuser sortboth" id="thuser"><a type='button' onclick='refreshUserDownloadsSort(0,"user","asc");'><?=$this->transEsc('User')?></a></th>
		                <th class="col-sm-2 table-align thtime sortboth" id="thtime"><a type='button' onclick='refreshUserDownloadsSort(0,"time","asc");'><?=$this->transEsc('Time')?></a></th>
		                <th class="col-sm-2 table-align thresource_path sortboth" id="thresource_path"><a type='button' onclick='refreshUserDownloadsSort(0,"resource_path","asc");'><?=$this->transEsc('Resource path')?></a></th>
		            </tr>
		        </thead>
		        <tbody class="ajaxinner">



		  <?


     foreach( $this->userdownload as  $item=>$index ){
     	echo "<tr>";
     	echo "<td>".$index['name']."</td>";
     	echo "<td>".$index['datetime']."</td>";
     	echo "<td>".$index['path']."</td>";
     	echo "</tr>";
     }
	          ?>
	          </tbody>
         	</table>
			</div>

                               <div id="pageDownload" class="alert alert-warning" style="text-align: center; display: none;">
                                </div>

			</div>
			</div>






			<div class="contentMenu col-sm-12">
				<div id="carouselImages">
					<div class="inner hidden">
						<img src="../../../themes/elar/images/arcadia_logo_n.gif" class="img-responsive" alt="Responsive image">
					</div>
					<div class="inner">
						<img src="../../../themes/elar/images/soas_60h189w.png" class="img-responsive" alt="Responsive image">
					</div>
				</div>
			</div>
  </div>



</div>
    <? }else { ?>
    
    <?=$this->flashmessages();?>
    
    <? } ?>
</div>
  
</div>
