<?
    // Set page title.
    $this->headTitle($this->translate('VuFind Administration - Private Statistics'));
?>

<? /*SCB datepicker*/ ?>

<script src="/themes/elar/js/bootstrap-datepicker.js"></script>
<link href="/themes/elar/css/datepicker.css" rel="stylesheet">
<script src="/themes/elar/js/admin/privatestatsdepositlist.js"></script>

<? /*SCB datepicker*/ ?>

<? /*SCB mapFocus Statistics*/ ?>


<?
	$s = $this->results;
?>


  

<? /*SCB mapFocus Statistics*/ ?>

<div class="row">
  <div class="sidebar col-sm-2">
  	<?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-10">
  <? if($this->request->get('PrivateStats')== 1){ ?>

  <div class="col-sm-5">
  <div class="border-facet">
				<? 
				//$current_year = date("Y");
				//$current_month = date('m', strtotime('-1 month'))+1;
				//$month = $_GET['month'];
                                //$year = $_GET['year'];

				//if (empty($year)) $year = $current_year;
				//if (empty($month)) $month = $current_month;
				
				$today = date('d/m/Y');
				$year = date('Y');
				$month = date('m');
				$day = date('d');
				
				?>
				<p class="menuHeader">
					<?=$this->transEsc('Private Statistics')?>
				</p>
				
				<div class="contentMenu">                
					<div class="post-content-right">
					
					<div class="form-group" align="center">
						<label class="control-label" for="email_message"><?=$this->transEsc('From')?>:</label>
						  <div>
						    <input type="text" value="<?=$today;?>" data-date-format="dd/mm/yyyy" id="datepickerFrom" name="datefrom" style="text-align: center;">
						  </div>
						  <label class=" control-label" for="email_message"><?=$this->transEsc('To')?>:</label>
						  <div>
						    <input type="text" value="<?=$today;?>" data-date-format="dd/mm/yyyy" id="datepickerTo" name="dateto" style="text-align: center;">
						  </div>
					</div>
					
					<script>
						$('#datepickerFrom').datepicker({
						   weekStart: 1 // day of the week start. 0 for Sunday - 6 for Saturday
						 });
						$('#datepickerTo').datepicker({
						   weekStart: 1 // day of the week start. 0 for Sunday - 6 for Saturday
						 });
					</script>
					
					
					<style>
						.datepicker{z-index:1151 !important;}
					</style>
					
					

						<div class="form-group" align="center">
						  <? echo '<a class="btn btn-default" type="button" onclick="filterELARWebTrafficDepositListsPrivate(0);"><i class="fa fa-filter" aria-hidden="true"></i> Filter</a>';?>
						</div>
						
						<div class="form-group" align="center">
						<?
						$dateObj   = DateTime::createFromFormat('!m', $month);
						$monthNameFrom = $dateObj->format('F');
						$dateObj   = DateTime::createFromFormat('!m', $month);
						$monthNameTo = $dateObj->format('F');
						?>
						<? echo '<span><i>'.$this->transEsc('Data from').' </i></span><span class="labelPublicStatsResultsFrom"><i>' . $year . ' ' . $monthNameFrom . ' ' . $day . '</i></span><i> '.$this->transEsc('to').' </i><span class="labelPublicStatsResultsTo"><i>' . $year . ' ' . $monthNameTo . ' ' . $day . '</i></span>'; ?>
						</div>

						<div class="stat_text_checkbox" align="left">
							<label><input type="checkbox"  value="All deposits" id="fundingbodyAll" name="fundingbody"  checked="yes"/><?=$this->transEsc('All deposits')?></label>
						<?
							$fundingBodies = $this->fundingbodies;
							foreach ($fundingBodies as $fb=>$k){
							echo '<label><input type="checkbox"  value="'.$k.'" id="fundingbody" name="fundingbody" class="fundingbody" disabled="true"/>'.$k.'</label>';
							}
						?>

						<script>
						    // Si se hace click sobre el input de tipo checkbox con id checkb
						    $('#fundingbodyAll').click(function() {
						        // Si esta seleccionado (si la propiedad checked es igual a true)
						        if ($(this).prop('checked')) {
						            // Selecciona cada input que tenga la clase .checar
						            $('.fundingbody').prop('checked', true);
						            $(".fundingbody").attr("disabled", true);
						        } else {
						            // Deselecciona cada input que tenga la clase .checar
						            $('.fundingbody').prop('checked', false);
						            $(".fundingbody").attr("disabled", false);
						        }
						    });
						</script>



						</div>

						<div class="stat_text_checkbox" align="left">
							<label style="display: inline-flex;"><input type="checkbox" value="Current" checked="yes" id="current_or_superseded" name="current_or_superseded"  checked="yes"/><?=$this->transEsc('Current')?></label>
							<label style="display: inline-flex;"><input type="checkbox" value="Superseded" id="current_or_superseded" name="current_or_superseded" /><?=$this->transEsc('Superseded')?></label>
						</div>


						<?
							$s = $this->results;
						?>
						


				   	</div>
				</div>
			</div>
		</div>
		
  <div class="col-sm-12">
  	<div class="border-facet">
				<p class="menuHeader">
					<?=$this->transEsc('Deposit List')?>
				</p>
				
				
				<form id="statisticsFormDepositos" name="statisticsFormDepositos" action='PrivateStatsDepositlist?yearFrom=<?=$year?>&monthFrom=<?=$month?>&dayFrom=<?=$day?>&yearTo=<?=$year?>&monthTo=<?=$month?>&dayTo=<?=$day?>&projectId=<?=$project_id?>' method="post">
				    <input type="hidden" name="btnExportarExcelDepositos" value="Exportar" />
				    <p class="contentMenu">
				    <?
				    echo $this->transEsc('CSV download info');
				    ?>
				    
				    <a class="csvlink" href="#" onclick="document.getElementById('statisticsFormDepositos').submit();" style="text-decoration: underline;">
				    <?
				    echo $this->transEsc('CSV file');
				    ?>
				    </a>
				    </p>
				</form>
				     <div id="example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">


         	<table id="example" class="table table-striped table-bordered" cellspacing="0" width="auto">
         		<thead>
		            <tr>
		                <th class="col-sm-2 table-align"><?=$this->transEsc('Node Id')?></th>
		                <th class="col-sm-2 table-align"><?=$this->transEsc('Deposit name')?></th>
		                <th class="col-sm-2 table-align"><?=$this->transEsc('Deposit Id')?></th>
		                <th class="col-sm-2 table-align"><?=$this->transEsc('Project Id')?></th>
		                <th class="col-sm-2 table-align"><?=$this->transEsc('Resources O')?></th>
		                <th class="col-sm-2 table-align"><?=$this->transEsc('Resources U')?></th>
		                <th class="col-sm-2 table-align"><?=$this->transEsc('Resources S')?></th>
		                <th class="col-sm-2 table-align"><?=$this->transEsc('Total resources')?></th>
		                <th class="col-sm-6 table-align"><?=$this->transEsc('Status')?></th>
		            </tr>
		        </thead>
		        <tbody class="ajaxinner">



		  <?
	          $urlSolr = 'http://'.$_SERVER['SERVER_NAME'].':8080/solr/biblio/select?q=format%3A%22Deposit%22&fl=id%2C+title%2C+corpusid%2C+deposit_status_string+project_id_number&wt=xml&indent=true&rows=1000';
	
	          $ch = curl_init();
	          curl_setopt($ch, CURLOPT_URL,$urlSolr);
	          curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	          curl_setopt($ch, CURLOPT_TIMEOUT, 5);
	          curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
	          $contentDepositTitle = curl_exec($ch);
	          curl_close($ch);
	          $xml = simplexml_load_string($contentDepositTitle, 'SimpleXMLElement', LIBXML_NOCDATA);
	
	$solrList = array();

	$listCount=0;
     	foreach( $xml->result->doc  as $result ) {
     		//echo "<tr>";
		$listOutput=array();
	foreach( $result->str as $str ) {
		if($str['name'] == 'id') {
			$listId= $str."";
			//echo "<td>".$listId."</td>";
			$listOutput['id'] = $listId;
		}
		if($str['name'] == 'title'){
                	$listTitle = $str."";
                	//echo "<td>".$listTitle."</td>";
			$listOutput['title'] = $listTitle;
                }
		if($str['name'] == 'corpusid'){
                	$listCorpus = $str."";
                	//echo "<td>".$listCorpus."</td>";
			$listOutput['corpusid'] = $listCorpus;
			
                }
        }
        $projectId="";
	foreach( $result->arr as $arr ){
		
		if($arr['name'] == 'project_id_number') {
			//echo "tiene".count($arr);
			foreach($arr as $arr_item){
				if ($projectId=="") {
					$projectId = $arr_item."";
				} else {
					$projectId = $projectId.", ".$arr_item."";
				}
			}

			
                }
     		//echo "</tr>"; 
        }
        $listOutput['projectId'] = $projectId;
	
	foreach( $result->arr as $arr ){
		if($arr['name'] == 'deposit_status_string') {
			$listStatus = $arr->str."";
			$listOutput['status'] = $listStatus;

                }
     		//echo "</tr>"; 
        }
	//$solrList[] = array('id'=>$listId, 'title'=>$listTitle, 'depositId'=>$listCorpus, 'status'=>$listStatus);
	$solrList[$listId] = array( 'title'=>$listTitle, 'depositId'=>$listCorpus, 'status'=>$listStatus, 'projectId'=>$projectId);
        $output[$listCount]=$listOutput;
        $listCount++;
     }
     foreach( $this->resources as  $item=>$index ){
     	echo "<tr>";
     	echo "<td>".$item."</td>";
     	$title=$this->transEsc('In progress');
     	$depositId=$this->transEsc('In progress');
     	$projectId=$this->transEsc('Other funding body');
     	$status=$this->transEsc('In progress');
     	foreach ($solrList[$item] as $indexElem=>$elem){
     		if ($indexElem=='title') $title = $elem;
     		if ($indexElem=='depositId') if ($elem!="") $depositId = $elem;
     		if ($indexElem=='projectId') if ($elem!="") $projectId = $elem;
     		if ($indexElem=='status') if ($elem!="") $status = $elem;
     	}
     	echo "<td>".$title."</td>";
     	echo "<td>".$depositId."</td>";
     	echo "<td>".$projectId."</td>";
     	$countO=0;
     	$countS=0;
     	$countU=0;
     	
     	foreach ($index as $subIndex=>$k){
     		foreach ($k as $j=>$l) {
     		if ($subIndex=='O') $countO = $l;
     		if ($subIndex=='U') $countU = $l;
     		if ($subIndex=='S') $countS = $l;
	        }
     	}
     	echo "<td>".$countO."</td>";
     	echo "<td>".$countU."</td>";
     	echo "<td>".$countS."</td>";
     	echo "<td>".(intval($countO)+intval($countS)+intval($countU))."</td>";
     	echo "<td>".$status."</td>";
     	echo "</tr>";
     }
     //print_r($this->resources);
     //print_r($solrList);
             //echo "<pre>";
             //print_r($output);
             //echo "</pre>";
	          ?>
	          </tbody>
         	</table>
			</div>
			</div>
			</div>










			<div class="contentMenu col-sm-12">
				<div id="carouselImages">
					<div class="inner hidden">
						<img src="../../../themes/elar/images/arcadia_logo_n.gif" class="img-responsive" alt="Responsive image">
					</div>
					<div class="inner">
						<img src="../../../themes/elar/images/soas_60h189w.png" class="img-responsive" alt="Responsive image">
					</div>
				</div>
			</div>
  </div>



</div>
    <? }else { ?>
    
    <?=$this->flashmessages();?>
    
    <? } ?>
</div>
  
</div>
