<h4><?=$this->transEsc('Your Account')?></h4>
<div class="list-group">
  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' ? ' active' : ''?>">
      <?=$this->transEsc('Favorites')?>
      <span class="pull-right flip"><i class="fa fa-fw fa-star"></i></span>
    </a>
  <? endif; ?>
  <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>

    <? if ($this->ils()->checkCapability('getMyProfile')): ?>
      <a href="<?=$this->url('myresearch-profile')?>" class="list-group-item<?=$this->active == 'profile' ? ' active' : ''?>">
        <?=$this->transEsc('Profile')?>
        <span class="pull-right flip"><i class="fa fa-fw fa-user"></i></span>
      </a>
    <? endif; ?>
    <? $user = $this->auth()->isLoggedIn(); if ($user && $user->libraryCardsEnabled()): ?>
      <a href="<?=$this->url('librarycards-home')?>" class="list-group-item<?=$this->active == 'librarycards' ? ' active' : ''?>">
        <?=$this->transEsc('Library Cards')?>
        <span class="pull-right flip"><i class="fa fa-fw fa-barcode"></i></span>
      </a>
    <? endif; ?>
  <? endif; ?>
  <a href="<?=$this->url('search-history')?>?require_login" class="list-group-item<?=$this->active == 'history' ? ' active' : ''?>">
    <?=$this->transEsc('history_saved_searches')?>
    <span class="pull-right flip"><i class="fa fa-fw fa-search"></i></span>
  </a>
  <? if ($user = $this->auth()->isLoggedIn()): ?>
    <a href="<?=$this->url('myresearch-logout')?>" class="list-group-item">
      <?=$this->transEsc("Log Out")?>
      <span class="pull-right flip"><i class="fa fa-fw fa-sign-out"></i></span>
    </a>
  <? endif; ?>
</div>
<? if ($this->auth()->isLoggedIn() && $this->auth()->getManager()->supportsPasswordChange()): ?>
  <h4><?=$this->transEsc('Preferences')?></h4>
  <div class="list-group">
    <a href="<?=$this->url('myresearch-changepassword') ?>" class="list-group-item<?=$this->active == 'newpassword' ? ' active' : ''?>">
      <?=$this->transEsc('Change Password') ?>
      <span class="pull-right flip"><i class="fa fa-fw fa-lock"></i></span>
    </a>
  </div>
<? endif; ?>
<? if ($this->userlist()->getMode() !== 'disabled' && $user = $this->auth()->isLoggedIn()): ?>
  <h4><?=$this->transEsc('Your Lists')?></h4>
  <div class="list-group">
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' ? ' active' : ''?>">
      <?=$this->transEsc('Your Favorites')?>
      <span class="pull-right flip"><i class="fa fa-fw fa-star"></i></span>
    </a>
    <? $lists = $user->getLists() ?>
    <? foreach ($lists as $list): ?>
        <a href="<?=$this->url('userList', array('id' => $list['id']))?>" class="list-group-item<?=$this->active == 'list' . $list['id'] ? ' active' : ''?>">
          <?=$this->escapeHtml($list['title'])?>
          <span class="badge"><?=$list->cnt?></span>
        </a>
    <? endforeach; ?>
    <a href="<?=$this->url('editList', array('id'=>'NEW'))?>" title="<?=$this->transEsc('Create a List') ?>" class="list-group-item">
      <?=$this->transEsc('Create a List') ?>
      <span class="pull-right flip"><i class="fa fa-fw fa-plus"></i></span>
    </a>
  </div>
<? endif ?>
