<?
  // Set page title.
  $this->headTitle($this->translate('statistics'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('statistics') . '</li>';
?>


<?
   $title = $this->title;
   
   echo '<h3><b>' . $title . '</b></h3>';
   
   $deposit = $_GET['node_id'];
   $user = $_GET['user'];
   //$month = $_GET['current_month'];
   //$year = $_GET['current_year'];
   $yearFrom = $_GET['yearFrom'];
   $monthFrom = $_GET['monthFrom'];
   $dayFrom = $_GET['dayFrom'];
   $yearTo = $_GET['yearTo'];
   $monthTo = $_GET['monthTo'];
   $dayTo = $_GET['dayTo'];
   
   $dateObj = DateTime::createFromFormat('!m', $monthFrom);
   $monthNameFrom = $dateObj->format('F');
   $dateObj = DateTime::createFromFormat('!m', $monthTo);
   $monthNameTo = $dateObj->format('F');
   
   $s = $this->results;
   
   if (empty($s)) {
   	echo '</br>';
   	echo "<i>" . $dayFrom . " " . $monthNameFrom . " " . $yearFrom . " - " . $dayTo . " " . $monthNameTo . " " . $yearTo . ": " . $this->transEsc('without statistics') . "</i>";
   	echo '</br>';
   } else {
   	echo '</br>';
   	
?>

<form id="statisticsForm" name="statisticsForm" action='Home?node_id=<?=$deposit?>&user=<?=$user?>&yearFrom=<?=$yearFrom?>&monthFrom=<?=$monthFrom?>&dayFrom=<?=$dayFrom?>&yearTo=<?=$yearTo?>&monthTo=<?=$monthTo?>&dayTo=<?=$dayTo?>' method="post">
    <input type="hidden" name="btnExportarExcel" value="Exportar" />
    
    <?
    echo "<i>" . $dayFrom . " " . $monthNameFrom . " " . $yearFrom . " - " . $dayTo . " " . $monthNameTo . " " . $yearTo . ": " .  $this->transEsc('CSV download info') . "</i>";
    ?>
    
    <a href="#" onclick="document.getElementById('statisticsForm').submit();" style="text-decoration: underline;">
    <?
    echo $this->transEsc('CSV file');
    ?>
    </a>
</form>

<? 
   echo '</br>';
   
   $first = True;
   
   foreach ($s as $valor) {
	   
   	$stat = explode(" - ", $valor);
   	// Muestra los campos de la BD
   	// date, time, firstname, surname, path
    	$day = $stat[0];
    	$timestamp1 = strtotime($last_day);
		$timestamp2 = strtotime($day);
		
	if($timestamp1 == $timestamp2){
	    echo "<tr><td class='col-sm-2'>" . $stat[1] . "</td><td class='col-sm-2'>" . $stat[2] . " " . $stat[3] . "</td><td class='col-sm-8'>" . $stat[4] . "</td><td class='col-sm-2'><a href='/Record/" . $stat[5] . "' target='_blank'>" . $stat[5] . "</a></td><td class='col-sm-2'>" . $stat[6] . "</td></tr>";
	}else{
	    if(!$first) {
	    	echo "</tbody></table></div>";
	    }
	    
	    $first = False;

	    echo "<h4><b>" . date("j F Y", $timestamp2) . "</b></h4>";
	    
	    echo "<div><table class='table' style='background-color: #cccccc; border-top: 3px solid #ffdd66;'><thead></thead><tbody>";
	    echo "<tr><td class='col-sm-2'>" . $stat[1] . "</td><td class='col-sm-2'>" . $stat[2] . " " . $stat[3] . "</td><td class='col-sm-8'>" . $stat[4] . "</td><td class='col-sm-2'><a href='/Record/" . $stat[5] . "' target='_blank'>" . $stat[5] . "</a></td><td class='col-sm-2'>" . $stat[6] . "</td></tr>";
	    
	    $last_day = $stat[0];
	}
	
   }
   
}

?>


