<?
    // Set page title.
    $this->headTitle($this->translate('VuFind Administration - Private Statistics'));
?>

<? /*SCB datepicker*/ ?>

<script src="/themes/elar/js/bootstrap-datepicker.js"></script>
<link href="/themes/elar/css/datepicker.css" rel="stylesheet">

<? /*SCB datepicker*/ ?>

<? /*SCB mapFocus Statistics*/ ?>

<link rel="stylesheet" media="all" href="/themes/elar/css/mapFocus/jquery-jvectormap.css"/>

<script src="/themes/elar/js/mapFocus/jquery-1.8.2.js"></script>
<script src="/themes/elar/js/mapFocus/jquery-jvectormap.js"></script>

<script src="/themes/elar/js/mapFocus/jquery-jvectormap-world-mill-en.js"></script>

<?
	$s = $this->results;
?>

<script>
    jQuery.noConflict();
    jQuery(function(){
    var $ = jQuery;
    });
    
  </script>
  

<? /*SCB mapFocus Statistics*/ ?>

<div class="row">
  <div class="sidebar col-sm-2">
  	<?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-10">
  <? if($this->request->get('PrivateStats')== 1){ ?>
  <div class="col-sm-5">
  <div class="border-facet">
				<? 

                                $today = date('d/m/Y');
                                $year = date('Y');
                                $month = date('m');
                                $day = date('d');



                                $dateFrom =  $this->dayFrom."/".$this->monthFrom."/". $this->yearFrom;
                                $dateTo =  $this->dayTo."/".$this->monthTo."/". $this->yearTo;
                                if($dateFrom=="//") {
                                $dateFrom =  $day."/".$month."/". $year;
                                $dateTo =  $day."/".$month."/". $year;
                                }
                                
				
				$today = date('d/m/Y');
				$year = date('Y');
				$month = date('m');
				$day = date('d');
				
				?>
				<p class="menuHeader">
					<?=$this->transEsc('Private Statistics')?>
				</p>
				
				<form id="statisticsForm" name="statisticsForm" action='UploadedFiles?yearFrom=<?=$year?>&monthFrom=<?=$month?>&dayFrom=<?=$day?>&yearTo=<?=$year?>&monthTo=<?=$month?>&dayTo=<?=$day?>' method="post">
				    <input type="hidden" name="btnExportarExcel" value="Exportar" />
				    <p class="contentMenu">
				    <?
				    echo $this->transEsc('CSV download info');
				    ?>
				    
				    <a class="csvlink" href="#" onclick="document.getElementById('statisticsForm').submit();" style="text-decoration: underline;">
				    <?
				    echo $this->transEsc('CSV file');
				    ?>
				    </a>
				    </p>
				</form>
				<div class="contentMenu">                
					<div class="post-content-right">

                                        <form id="uploadedfiles" name="uploadedfiles" action="<?=$this->url('admin/uploadedfiles')?>" method="get">	
					<div class="form-group" align="center">
						<label class="control-label" for="email_message"><?=$this->transEsc('From')?>:</label>
						  <div>
						    <input type="text" value="<?=$dateFrom;?>" data-date-format="dd/mm/yyyy" id="datepickerFrom" name="datefrom" style="text-align: center;">
						  </div>
						  <label class=" control-label" for="email_message"><?=$this->transEsc('To')?>:</label>
						  <div>
						    <input type="text" value="<?=$dateTo;?>" data-date-format="dd/mm/yyyy" id="datepickerTo" name="dateto" style="text-align: center;">
						  </div>
					</div>
					
					<script>
						$('#datepickerFrom').datepicker({
						   weekStart: 1 // day of the week start. 0 for Sunday - 6 for Saturday
						 });
						$('#datepickerTo').datepicker({
						   weekStart: 1 // day of the week start. 0 for Sunday - 6 for Saturday
						 });
					</script>
					
					
					<style>
						.datepicker{z-index:1151 !important;}
					</style>
					
					
						<div class="form-group" align="center">
						  <? echo '<a class="btn btn-default" type="button" onclick="filterELARWebTrafficPrivate();"><i class="fa fa-filter" aria-hidden="true"></i> Filter</a>';?>
                                                  <? echo '<a class="btn btn-default" type="submit" onclick="uploadedfiles.submit();"><i class="fa fa-filter" aria-hidden="true"></i> FilterNew</a>';?>
						</div>
                                                </form>
						
						<div class="form-group" align="center">
						<?
						$dateObj   = DateTime::createFromFormat('!m', $month);
						$monthNameFrom = $dateObj->format('F');
						$dateObj   = DateTime::createFromFormat('!m', $month);
						$monthNameTo = $dateObj->format('F');
						?>
						<? echo '<span><i>'.$this->transEsc('Data from').' </i></span><span class="labelPublicStatsResultsFrom"><i>' . $year . ' ' . $monthNameFrom . ' ' . $day . '</i></span><i> '.$this->transEsc('to').' </i><span class="labelPublicStatsResultsTo"><i>' . $year . ' ' . $monthNameTo . ' ' . $day . '</i></span>'; ?>
						</div>
						
						<?
							$s = $this->results;
						?>
						

				   	</div>
				</div>
			</div>
		</div>
		

  <div class="col-sm-12">
  	<div class="border-facet">
				<p class="menuHeader">
					<?=$this->transEsc('Uploaded files')?>
				</p>
				
				
				<form id="statisticsFormUploadedFiles" name="statisticsFormUploadedFiles" action='PrivateStats?yearFrom=<?=$year?>&monthFrom=<?=$month?>&dayFrom=<?=$day?>&yearTo=<?=$year?>&monthTo=<?=$month?>&dayTo=<?=$day?>' method="post">
				    <input type="hidden" name="btnExportarExcelUploadedFiles" value="Exportar" />
				    <p class="contentMenu">
				    <?
				    echo $this->transEsc('CSV download info');
				    ?>
				    
				    <a class="csvlink" href="#" onclick="document.getElementById('statisticsFormUploadedFiles').submit();" style="text-decoration: underline;">
				    <?
				    echo $this->transEsc('CSV file');
				    ?>
				    </a>
				    </p>
				<div id="limit_alert" class="alert alert-warning" style="text-align: center; display: none;">
					<?
                                    		echo $this->transEsc('The result is too big. Only the last 10000 uploaded files are shown.');
                                    	?>
				</div>
				
				</form>
				     <div id="example3_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">


         	<table id="example3" class="table table-striped table-bordered" cellspacing="0" width="auto">
         		<thead>
		            <tr>
                                <th class="col-sm-2 table-align"><?=$this->transEsc('Deposit ID')?></th>
                                <th class="col-sm-2 table-align"><?=$this->transEsc('Deposit Title')?></th>
		                <th class="col-sm-2 table-align"><?=$this->transEsc('Uploaded date')?></th>
		                <th class="col-sm-2 table-align"><?=$this->transEsc('bundle ID')?></th>
		                <? /*<th class="col-sm-2 table-align"><?=$this->transEsc('Bundle Title')?></th>*/ ?>
				<th class="col-sm-2 table-align"><?=$this->transEsc('File Name')?></th>
                                <th class="col-sm-2 table-align"><?=$this->transEsc('Access')?></th>
                                <th class="col-sm-2 table-align"><?=$this->transEsc('Size (bytes)')?></th>
                                <th class="col-sm-2 table-align"><?=$this->transEsc('Duration (seconds)')?></th>
                                <th class="col-sm-2 table-align"><?=$this->transEsc('File type')?></th>
		            </tr>
		        </thead>
		        <tbody class="ajaxinner">



		  <?


     foreach( $this->uploadedfiles as  $item=>$index ){
     	echo "<tr>";
	echo "<td>".$index['deposit_id']."</td>";
        echo "<td>".$index['deposit_title']."</td>";
     	echo "<td>".$index['datetime']."</td>";
     	//echo "<td>".$index['id']."</td>";
	echo "<td><a href='/Record/" . $index['id'] . "' target='_blank'>" . $index['id'] . "</a></td>";
     	//echo "<td>".$index['bundle_title']."</td>";
	//echo "<td>".$index['name']."</td>";
	echo "<td>".end(explode('/',$index['name']))."</td>";	
        echo "<td>".$index['accessavailability']."</td>";
        echo "<td>".$index['size']."</td>";
        echo "<td>".$index['duration']."</td>";
        echo "<td>".$index['file_type']."</td>";
     	echo "</tr>";
     }
	          ?>
	          </tbody>
         	</table>
			</div>
			</div>
			</div>

			<div class="contentMenu col-sm-12">
				<div id="carouselImages">
					<div class="inner hidden">
						<img src="../../../themes/elar/images/arcadia_logo_n.gif" class="img-responsive" alt="Responsive image">
					</div>
					<div class="inner">
						<img src="../../../themes/elar/images/soas_60h189w.png" class="img-responsive" alt="Responsive image">
					</div>
				</div>
			</div>
  </div>



</div>
    <? }else { ?>
    
    <?=$this->flashmessages();?>
    
    <? } ?>
</div>
  
</div>
